# Generated by Django 3.0.2 on 2020-02-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_column='firstName', max_length=12)),
                ('last_name', models.CharField(blank=True, db_column='lastName', max_length=18, null=True)),
                ('years_pro', models.IntegerField(db_column='yearsPro')),
                ('college_name', models.CharField(blank=True, db_column='collegeName', max_length=34, null=True)),
                ('country', models.CharField(blank=True, max_length=32, null=True)),
                ('dob', models.DateField(blank=True, db_column='DOB', null=True)),
                ('affiliation', models.CharField(blank=True, max_length=50, null=True)),
                ('height_in_meters', models.DecimalField(blank=True, db_column='heightInMeters', decimal_places=2, max_digits=4, null=True)),
                ('weight_in_kilograms', models.DecimalField(blank=True, db_column='weightInKilograms', decimal_places=1, max_digits=5, null=True)),
                ('pos', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'db_table': 'players',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=13)),
                ('full_name', models.CharField(db_column='fullName', max_length=22)),
                ('nick_name', models.CharField(db_column='nickName', max_length=13)),
                ('logo', models.CharField(max_length=138)),
                ('short_name', models.CharField(db_column='shortName', max_length=3)),
                ('conf_name', models.CharField(db_column='confName', max_length=4)),
                ('div_name', models.CharField(db_column='divName', max_length=9)),
            ],
            options={
                'db_table': 'teams',
                'managed': False,
            },
        ),
    ]
