# Generated by Django 3.0.2 on 2020-02-06 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Standing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win', models.IntegerField()),
                ('loss', models.IntegerField()),
                ('conference', models.CharField(max_length=4)),
                ('conference_rank', models.IntegerField()),
                ('division', models.CharField(max_length=20)),
                ('division_rank', models.IntegerField()),
                ('team_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_time', models.CharField(max_length=50)),
                ('home_score', models.IntegerField()),
                ('away_score', models.IntegerField()),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away', to='app.Team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home', to='app.Team')),
            ],
        ),
    ]
