# Generated by Django 3.0.2 on 2020-02-11 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_game_standing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standing',
            name='id',
        ),
        migrations.AlterField(
            model_name='standing',
            name='team_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.Team'),
        ),
    ]
