# Generated by Django 3.0.2 on 2020-02-11 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200211_2024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='standing',
            old_name='team_id',
            new_name='team',
        ),
    ]
